version: 0.0.1   # Required
apimServiceName: fancy   # Required, must match name of an apim service deployed in the specified resource group
apiVersionSet:   # Optional
    id: myVersionSetID
    displayName: myAPIVersionSet
    description: a description
    versioningScheme: Query
    versionQueryName: versionQuery
    versionHeaderName: versionHeader
api:
  name: myAPI   # Required
  openApiSpec: https://dotnetcore-api-app.azurewebsites.net/swagger/v1/swagger.json    # Required, can be url or local file
  #openApiSpec: https://petstore.swagger.io/v2/swagger.json
  policy: C:\Users\shkhose\source\repos\azure-api-management-devops-example\ToDoAPI\input\apiPolicyHeaders.xml  # Optional, can be url or local file
  suffix: myAPIPet   # Required
  apiVersion: v1   # Optional
  apiVersionDescription: My first version   # Optional 
  apiVersionSetId: myVersionSetID
  revision: 1   # Optional
  revisionDescription: My first revision   # Optional
  operations:   # Optional
    ApiTodoByIdGet: # Must match the operationId property of a path's operations
      policy: C:\Users\shkhose\source\repos\azure-api-management-devops-example\ToDoAPI\input\operationRateLimit.xml  # Optional, can be url or local file
    ApiTodoGet:  # Must match the operationId property of a path's operations
      policy: C:\Users\shkhose\source\repos\azure-api-management-devops-example\ToDoAPI\input\operationRateLimit.xml   # Optional, can be url or local file
  authenticationSettings:   # Optional
    subscriptionKeyRequired: false
    #oAuth2:
    #    authorizationServerId: apimgmtaad
    #    scope: scope
  products: starter    # Optional, adds api to the specified products
outputLocation: C:\Users\shkhose\source\repos\azure-api-management-devops-example\ToDoAPI\output  # Required, folder the creator will write the templates to
linked: true   # Optional
linkedTemplatesBaseUrl : C:\Users\shkhose\source\repos\azure-api-management-devops-example\ToDoAPI\output  # Required if 'linked' property is set to true