version: 0.0.1
apimServiceName: testapimlucas
apiVersionSet:
    displayName: myAPIVersionSet
    description: a description
    versioningScheme: Query
    versionQueryName: versionQuery
    versionHeaderName: versionHeader
api:
  name: myAPI
  policy: C:\Users\lucashh\Desktop\Projects\APIM-ARM\azure-api-management-devops-example\src\APIM_ARMTemplate\apimtemplate\Creator\ExampleFiles\XMLPolicies\apiPolicyHeaders.xml
  suffix: conf
  apiVersion: v1
  apiVersionDescription: My first version
  revision: 1
  revisionDescription: My first revision
  operations:
    addPet: 
      policy: C:\Users\lucashh\Desktop\Projects\APIM-ARM\azure-api-management-devops-example\src\APIM_ARMTemplate\apimtemplate\Creator\ExampleFiles\XMLPolicies\operationRateLimit.xml
    deletePet: 
      policy: C:\Users\lucashh\Desktop\Projects\APIM-ARM\azure-api-management-devops-example\src\APIM_ARMTemplate\apimtemplate\Creator\ExampleFiles\XMLPolicies\operationRateLimit.xml
  authenticationSettings:
    subscriptionKeyRequired: false
    oAuth2:
        authorizationServerId: serverId
        scope: scope
  products: starter, platinum
outputLocation: C:\Users\lucashh\Desktop\Projects\APIM-ARM\GeneratedTemplates
linked: false
linkedTemplatesBaseUrl : https://lucasyamlblob.blob.core.windows.net/yaml